In [70]:
from matplotlib import pyplot as plt #for plots
import numpy as np
import pandas as pd #data
import tkinter
from tkinter.filedialog import askopenfilename
import seaborn as sns #for the more beautiful plots
import math
from matplotlib.colors import LogNorm
import scipy.io as scpio
import scipy.signal
import glob
import cv2
import matplotlib.image as mpimg
from matplotlib.widgets import Slider, Button
import os
import glob
import re
import matplotlib as mpl
import scipy
from pathlib import Path

In [2]:
plt.rcParams['figure.figsize']=(20,20)
plt.rcParams['axes.labelsize']=12
plt.rcParams['xtick.labelsize']=12
plt.rcParams['ytick.labelsize']=12
plt.rcParams['legend.fontsize']=12
plt.rcParams['legend.title_fontsize']=14
plt.rcParams['legend.markerscale']=1
plt.rcParams['legend.loc']='upper right'
sns.set_style('white')

In [ ]:
path="E:\RWTH_Aachen\Promo\iNano\WTH\\indents_area_xx\\area29" ##double \\ if number ist after\
file="area29_overview.tif"

In [ ]:
print(easygui.fileopenbox())

In [3]:
%matplotlib inline
img = mpimg.imread(path+'\\'+file)
imgplot = plt.imshow(img)
plt.show()

NameError: name 'path' is not defined

In [4]:
indents_y=1 # grid shape of the indents
indents_x=25

In [5]:
size_x=img.shape[0]
size_y=img.shape[1]

NameError: name 'img' is not defined

In [20]:
init=Path('J:/Users/Berners, Lukas/Thetascan')
file = Path(askopenfilename(initialdir=init, title='´Select the folder, with images you want to normalise and select first image'))


In [21]:
#file = Path(askopenfilename(initialdir='I:\LEO', title='´Select the folder, with images you want to normalise and select first image'))
#paths=list(file.parent.glob('**/pano*.tif'))
#os.mkdir(file.parent / 'normalised')

# path='I:\\XRD\\Thetascan\\Martina'
# file='Mg2Ca_merged.txt'

# prof=np.loadtxt(path + '\\' +file)


# path='I:\\XRD\\Thetascan\\Nadia\\1503\\2'
# file='1503_2mm_exported.xy'
prof2=np.loadtxt(file,skiprows=1)

In [22]:
%matplotlib

#plt.plot(prof[:,0],prof[:,1])
plt.plot(prof2[:,0],prof2[:,1])

Using matplotlib backend: Qt5Agg


In [ ]:
prof[:,0]

In [30]:
crds=get_coords(prof,20)
crds

array([[3.50917339e+01, 4.02723960e+05],
       [3.76480511e+01, 3.24907621e+05],
       [5.10350806e+01, 1.31582651e+05],
       [8.17781586e+01, 3.43122265e+04],
       [1.00950538e+02, 2.70169447e+04],
       [1.08484946e+02, 2.58010644e+04],
       [1.24764651e+02, 2.09375431e+04]])

In [67]:
params=scipy.optimize.curve_fit(quadr_bkg,prof[:,0],prof[:,1])

RuntimeError: Optimal parameters not found: Number of calls to function has reached maxfev = 1200.

In [76]:
pks=scipy.signal.find_peaks_cwt(prof[:,1],widths=5)
plt.plot(prof[:,0],prof[:,1])
plt.scatter(prof[pks,0],prof[pks,1])

In [68]:
params


(array([ 9.93504252e+05, -2.03871457e+04,  1.05055567e+02,  1.00000000e+00,
         1.00000000e+00]),
 array([[inf, inf, inf, inf, inf],
        [inf, inf, inf, inf, inf],
        [inf, inf, inf, inf, inf],
        [inf, inf, inf, inf, inf],
        [inf, inf, inf, inf, inf]]))

In [63]:
cheb=np.polynomial.chebyshev.chebfit(crds[:,0],crds[:,1],2)

In [64]:
plt.plot(prof[:,0],prof[:,1])
x=np.arange(35,135,1)
#plt.plot(crds[:,0],quadr_bkg(crds[:,0],cheb[0],cheb[1],cheb[2],cheb[3],cheb[4]))
plt.plot(x,quadr_bkg(x,params[0][0],params[0][1],params[0][2],params[0][3],params[0][4]))#,params[0][5]))
#plt.plot(prof[:,0],np.polynomial.chebyshev.chebval(prof[:,0],cheb))

In [48]:
x

array([ 35,  36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,
        48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,
        61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,
        74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,
        87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99,
       100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134])

In [41]:
plt.plot(prof[:,0],)

In [42]:
np.savetxt('background.txt',(prof[:,0],np.polynomial.chebyshev.chebval(prof[:,0],cheb)),newline='\n')

In [54]:
(prof[:,0],np.polynomial.chebyshev.chebval(prof[:,0],cheb))

(array([ 35.  ,  35.01,  35.02, ..., 125.98, 125.99, 126.  ]),
 array([356960.07398301, 356850.06900873, 356740.08092764, ...,
         55213.16770993,  55256.85699744,  55300.56317813]))

In [66]:
def quadr_bkg(x,c0,c1,c2,c3=0,c4=0):
    return c0+c1*x+c2*x**+c3*x**3+c4*x**4

__Make some nice Function definitons__

In [24]:
global ix, iy
def onclick(event):
    ix, iy = event.xdata, event.ydata
    print('x = %d, y = %d'.format(ix, iy))

    global coords
    coords.append([ix, iy])

    if len(coords) == 2:
        fig.canvas.mpl_disconnect(cid)

In [25]:
def get_coords(profile,no=2):
    #%matplotlib
    fig, ax = plt.subplots()
    ax.plot(profile[:,0],profile[:,1])
    coords=fig.ginput(n=no,timeout=no*5)
    #cid = fig.canvas.mpl_connect('button_press_event', onclick)
    crds=np.array(coords)

    return crds

In [26]:
def linfunc(pos,parallel,x):
    m=(parallel[0,1]-parallel[1,1])/(parallel[0,0]-parallel[1,0])
    #print(m)
    b=pos[1]-m*pos[0]
    #print(x)
    return m*x+b

In [27]:
def get_scale_img(img,real_length=20):
    print('please press the coords of the scalebar')
    bar=get_coords(img)
    scale_length=abs(bar[0,0]-bar[1,0])
    micppx=real_length/scale_length
    size_mic_x=micppx*img.shape[0]
    size_mic_y=micppx*img.shape[1]
    return micppx,[size_mic_x,size_mic_y]

In [28]:
%matplotlib
micppx,size_mic=get_scale_img(img,20)

Using matplotlib backend: Qt5Agg


NameError: name 'img' is not defined

In [29]:

fig, ax = plt.subplots()
ax.imshow(img)
if_coords=fig.ginput(n=2)
inf=np.array(if_coords)

NameError: name 'img' is not defined

In [ ]:
inf[0,0]

__Try to name the indents based on coordinates clicked with the mouse__

In [ ]:
%matplotlib
print('please press the coords of the first two indents scheme:') ## 1 -> 2 -> x next to 1 i.e. if the grid is 15x3 it would be 1st, 2nd and 4th indent
if indents_y>1:
    no=3
else:
    no=2
crds=get_coords(img,no)

array = np.arange(indents_y*indents_x).reshape((indents_x,indents_y))
if no==3: #yes this is not the most logical setup xD
    dely=crds[0]-crds[1]
    delx=crds[0]-crds[2]
else:
    delx=crds[0]-crds[1]
    dely=[0,0]
#plt.plot(crds[:,0],crds[:,1])
distances=[]
for i in range(len(array)):
    for j in array[i]:
        #print(j)
        #print(dely[0])
        if indents_y>1:
            posx=crds[0,0]-dely[0]*(j%indents_y)/(indents_y-1)-delx[0]*i/(indents_x-1)
            posy=crds[0,1]-dely[1]*(j%indents_y)/(indents_y-1)-delx[1]*i/(indents_x-1)
        else:
            posx=crds[0,0]-delx[0]*i/(indents_x-1)
            posy=crds[0,1]-delx[1]*i/(indents_x-1)
        dist=abs( (inf[1,0]-inf[0,0])*(inf[0,1]-posy) - (inf[0,0]-posx)*(inf[1,1]-inf[0,1]) )/ np.sqrt( (inf[1,0]-inf[0,0])**2 + (inf[1,1]-inf[0,1])**2) #https://en.wikipedia.org/wiki/Distance_from_a_point_to_a_line
        #print(dist*micppx)
        distances.append([j,dist*micppx])
        plt.annotate(j+1,(posx,posy),bbox=dict(facecolor='white', alpha=0.5))
plt.savefig(path + '\\' +re.split('\.',file)[0] + '_named.' + re.split('\.',file)[1],bbox_inches='tight')
        #plt.plot((crds[0,0]-dely[0]*(j%4)/(indents_y-1)-delx[0]*i/(indents_x-1),crds[0,1]-dely[1]*(j%4)/(indents_y-1)-delx[1]*i/(indents_x-1)))
        #(crds[0]-crds[1])*array

In [ ]:

fig, ax = plt.subplots()
ax.imshow(img)
if_coords=fig.ginput(n=2)
inf=np.array(if_coords)

__Load in the indentation data__

In [ ]:
usrpath="E:\RWTH_Aachen\Promo\iNano\iNano"
#icurr=11
#folder=usrpath+'\\{}\DB_Files\{}\Cole\Mapping\EBSD\{}\{}'.format(foldername,usr,proj_name,samp_name)
areas=os.listdir(usrpath)
csvs=glob.glob(usrpath+"*\\**\\*.csv",recursive=True)


In [ ]:
indents=pd.DataFrame()
for key in csvs: 
    if re.match(r'.*_Test.*',key):
            #print(key)
            df1=pd.read_csv(key,header=[0,1],sep=",")
            df1['name']=key
            #print(df1.loc[0:1])
            indents=pd.concat([indents,df1],ignore_index=True)

indents[['Area','Test']]=indents.name.str.extract(r'((?<=area)\d*).*((?<=Test)\d*)')

In [ ]:
curr=indents[indents['Area']=='27']

In [ ]:
curr['dist']=""
for i in range(len(distances)):
    #print(i)
    curr.loc[curr['Test']==str(i),'dist']=distances[i][1]
    print(distances[i][1])

In [ ]:
curr

In [ ]:
cmap=mpl.cm.viridis
dis=np.array(distances)
curr=indents[indents['Area']=='29'] #select the area from above
curr=curr[curr['name'].str.contains('lower')]
curr['dist']=""
for i in range(len(distances)):
    #print(i)
    curr.loc[curr['Test']==str(i),'dist']=distances[i][1]
    print(distances[i][1])
curr_n=curr[~curr['Test'].isin(str(i) for i in [8,9,13,14,22,23,24,25])]
curr_n=curr
i=0
for i in range(len(dis)):
    df=curr_n[curr_n['Test']==str(i)]
    plt.plot(df['DEPTH'],df['Load'],color=cmap(dis[i,1]/max(curr_n['dist'])))
    #print(i)
    i=i+1
norm = mpl.colors.Normalize(vmin=0, vmax=max(curr_n['dist']))
  
# creating ScalarMappable
sm = plt.cm.ScalarMappable(cmap=cmap, norm=norm)
sm.set_array([])
plt.xlabel("Depth / nm")
plt.ylabel('Load / mN')
plt.colorbar(sm, ticks=np.linspace(0, max(curr_n['dist']),7),label='Distance from Surface / nm')

In [ ]:
curr[curr['name'].str.contains('lower')]
#curr['name']

In [ ]:
clen(curr['Test'].unique())

In [ ]:
curr_n=curr[~curr['Test'].isin(str(i) for i in [9,10,13,16,17,18,19,20,21,22,23,24,25])]
curr_n

In [ ]:
cmap = mpl.cm.cool
norm = mpl.colors.Normalize(vmin=0, vmax=max(dis[:,1]))

In [ ]:
cmap(0.5)

In [ ]:
fig, ax = plt.subplots(figsize=(6, 1))
fig.subplots_adjust(bottom=0.5)
fig.colorbar(mpl.cm.ScalarMappable(norm=norm, cmap=cmap),
             cax=ax, orientation='horizontal', label='Some Units')

In [ ]:
for i in range(len(pal)):
    print(pal[i])

In [ ]:
curr['dist']

In [ ]:
for i in range(len(distances)):
    #print(i)
    curr.loc[curr['Test']==str(i),'dist']=distances[i][1]
    print(distances[i][1])

In [ ]:
type(distances[i][1])

In [ ]:
distances[i][1]

In [ ]:
pip install jupyter_contrib_nbextensions

In [ ]:

print('please press the coords of the first two indents scheme:') ## 1 -> 2 -> x next to 1 i.e. if the grid is 15x3 it would be 1st, 2nd and 4th indent
if indents_y>1:
    no=3
else:
    no=2
crds=get_coords(img,no)

array = np.arange(indents_y*indents_x).reshape((indents_x,indents_y))
if no==3: #yes this is not the most logical setup xD
    dely=crds[0]-crds[1]
    delx=crds[0]-crds[2]
else:
    delx=crds[0]-crds[1]
    dely=[0,0]
#plt.plot(crds[:,0],crds[:,1])
for i in range(len(array)):
    for j in array[i]:
        #print(j)
        #print(dely[0])
        if indents_y>1:
            posx=crds[0,0]-dely[0]*(j%indents_y)/(indents_y-1)-delx[0]*i/(indents_x-1)
            posy=crds[0,1]-dely[1]*(j%indents_y)/(indents_y-1)-delx[1]*i/(indents_x-1)
        else:
            posx=crds[0,0]-delx[0]*i/(indents_x-1)
            posy=crds[0,1]-delx[1]*i/(indents_x-1)
        plt.scatter(posx,posy,marker="2",color='black')
